name: Review

on: pull_request

jobs:

  drupal-lint:
    runs-on: ubicloud-standard-4
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v4

    - name: Lint Drupal
      run: |
        docker compose run --rm drupal-lint

  drupal-check:
    runs-on: ubicloud-standard-4
    steps:
    - uses: actions/checkout@v4

    - name: Drupal Deprecations and Analysis Check
      run: |
        docker compose run --rm drupal-check
      env:
        DRUPAL_RECOMMENDED_PROJECT: ${{ secrets.DRUPAL_RECOMMENDED_PROJECT }}
